version: '3.8'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:80"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    networks:
      - vue-net

networks:
  vue-net:
    driver: bridge
