apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: frontend 
    spec:
      containers:
      - name: frontend
        image: ghcr.io/nosenadayo/challenge_talana_frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80